# CMake generated Testfile for 
# Source directory: /mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests
# Build directory: /mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ConvexityTest.Quadratic2DisConvex "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.Quadratic2DisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.Quadratic2DisConvex PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.QuadraticNDisConvex "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.QuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.QuadraticNDisConvex PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.OtherQuadraticNDisConvex "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.OtherQuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.OtherQuadraticNDisConvex PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.YetAnotherQuadraticNDisConvex "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.YetAnotherQuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.YetAnotherQuadraticNDisConvex PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsConvexOnCertainInterval "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsConvexOnCertainInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsConvexOnCertainInterval PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval "/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/home/fcr/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/GoogleTest.cmake;402;add_test;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/mnt/e/Bern_temp/optimization/ex2/aopt-exercise2/ConvexityTests/CMakeLists.txt;0;")
